// ===== Outros Companheiros - Builds =====

const COMPANIONS = {
    astarion: {
        id: 'astarion',
        name: 'Astarion',
        emoji: '🗡️',
        role: 'DPS Furtivo',
        race: 'Vampire Spawn (High Elf)',
        class: 'Rogue',
        subclass: 'Assassin',
        description: 'Mestre do stealth e dano crítico. Assassin garante critical hit em inimigos surpresos, e Sneak Attack escala absurdamente.',
        color: 'astarion',
        stats: {
            FOR: 8, DES: 17, CON: 14,
            INT: 13, SAB: 13, CAR: 10
        },
        estiloLuta: 'Nenhuma (Rogue)',
        background: 'Noble (Insight + Persuasion)',
        habilidadesChave: ['Sneak Attack', 'Assassinate', 'Cunning Action', 'Evasion'],
        magias: [],
        progressao: [
            { nivel: 1, classe: 'Rogue', escolhas: 'Sneak Attack 1d6, Expertise (Stealth + Sleight of Hand)' },
            { nivel: 2, classe: 'Rogue', escolhas: 'Cunning Action (Dash/Disengage/Hide como ação bônus)' },
            { nivel: 3, classe: 'Rogue', escolhas: '⭐ Assassin — Critical garantido em inimigos surpresos!' },
            { nivel: 4, classe: 'Rogue', escolhas: '⭐ Talento: Sharpshooter (se usar arco) ou +2 DES' },
            { nivel: 5, classe: 'Rogue', escolhas: 'Sneak Attack 3d6, Uncanny Dodge' },
            { nivel: 6, classe: 'Rogue', escolhas: 'Expertise extra (mais perícias)' },
            { nivel: 7, classe: 'Rogue', escolhas: 'Evasion (dano de área reduzido)' },
            { nivel: 8, classe: 'Rogue', escolhas: '⭐ Talento: +2 DES → 20 ou Alert' },
            { nivel: 9, classe: 'Rogue', escolhas: 'Sneak Attack 5d6' },
            { nivel: 10, classe: 'Rogue', escolhas: 'Talento: Ability Improvement' },
            { nivel: 11, classe: 'Rogue', escolhas: 'Reliable Talent (mínimo 10 nos dados de perícia)' },
            { nivel: 12, classe: 'Rogue', escolhas: 'Sneak Attack 6d6 — Dano máximo!' },
        ],
        combo: [
            'Sempre ataque de stealth para Surpresa',
            'Assassin = crítico garantido no primeiro turno',
            'Sneak Attack com crítico = dano massivo',
            'Cunning Action: Hide → ataca → Hide de novo'
        ],
        equipamentos: [
            { nome: 'The Deathstalker Mantle', nota: 'Invisibilidade após matar' },
            { nome: 'Knife of the Undermountain King', nota: 'Crítico melhor' },
            { nome: 'Leather Armor +2', nota: 'Bom AC + stealth' },
            { nome: 'Boots of Speed', nota: 'Dash como ação bônus extra' }
        ]
    },
    gale: {
        id: 'gale',
        name: 'Gale',
        emoji: '✨',
        role: 'DPS Mágico',
        race: 'Human',
        class: 'Wizard',
        subclass: 'Evocation',
        description: 'Mago de dano puro. Evocation permite lançar feitiços em área sem acertar aliados. Fireball goes brrr.',
        color: 'gale',
        stats: {
            FOR: 8, DES: 14, CON: 14,
            INT: 17, SAB: 10, CAR: 12
        },
        estiloLuta: 'N/A (Wizard)',
        background: 'Sage (Arcana + History)',
        habilidadesChave: ['Arcane Recovery', 'Sculpt Spells', 'Empowered Evocation', 'Arcane Ward'],
        magias: ['Fireball', 'Magic Missile', 'Counterspell', 'Haste', 'Hypnotic Pattern', 'Shield'],
        progressao: [
            { nivel: 1, classe: 'Wizard', escolhas: 'Arcane Recovery, Spells: Magic Missile, Shield, Mage Armor' },
            { nivel: 2, classe: 'Wizard', escolhas: '⭐ Evocation — Sculpt Spells (não acerta aliados!)' },
            { nivel: 3, classe: 'Wizard', escolhas: 'Fireball e Counterspell disponíveis!' },
            { nivel: 4, classe: 'Wizard', escolhas: '⭐ Talento: +2 INT → 18 ou War Caster' },
            { nivel: 5, classe: 'Wizard', escolhas: 'Fireball! Dano de área devastador' },
            { nivel: 6, classe: 'Wizard', escolhas: 'Potent Cantrip, slots de nível 4' },
            { nivel: 7, classe: 'Wizard', escolhas: 'Conjure Elemental, Greater Invisibility' },
            { nivel: 8, classe: 'Wizard', escolhas: '⭐ Talento: +2 INT → 20' },
            { nivel: 9, classe: 'Wizard', escolhas: 'Wall of Force, Telekinesis' },
            { nivel: 10, classe: 'Wizard', escolhas: 'Empowered Evocation (+INT no dano de evocação)' },
            { nivel: 11, classe: 'Wizard', escolhas: 'Chain Lightning, Disintegrate' },
            { nivel: 12, classe: 'Wizard', escolhas: '⭐ Overchannel (dano máximo em magias baixas)' },
        ],
        combo: [
            'Mage Armor + Shield = AC alta pra mago',
            'Haste no aliado mais forte (Karlach ou Lae\'zel)',
            'Fireball em área (Sculpt Spells protege aliados)',
            'Counterspell pra cancelar magias inimigas'
        ],
        equipamentos: [
            { nome: 'Staff of Spellpower', nota: '+1 DC de magia' },
            { nome: 'Robe of the Weave', nota: 'AC + bônus mágico' },
            { nome: 'Cloak of Protection', nota: '+1 AC e saves' },
            { nome: 'Amulet of Greater Health', nota: 'CON alta' }
        ]
    },
    wyll: {
        id: 'wyll',
        name: 'Wyll',
        emoji: '😈',
        role: 'DPS Ranged / Melee',
        race: 'Human',
        class: 'Warlock',
        subclass: 'The Fiend (Pact of the Blade)',
        description: 'O Blade of Frontiers. Eldritch Blast é o cantrip mais forte do jogo, e Pact of the Blade permite usar armas mágicas com carisma.',
        color: 'wyll',
        stats: {
            FOR: 8, DES: 13, CON: 14,
            INT: 10, SAB: 12, CAR: 17
        },
        estiloLuta: 'Pact of the Blade',
        background: 'Folk Hero (Athletics + Survival)',
        habilidadesChave: ['Eldritch Blast', 'Agonizing Blast', 'Pact of the Blade', 'Dark One\'s Blessing'],
        magias: ['Eldritch Blast', 'Hex', 'Hold Person', 'Counterspell', 'Hunger of Hadar'],
        progressao: [
            { nivel: 1, classe: 'Warlock', escolhas: 'Eldritch Blast, Dark One\'s Blessing (HP ao matar)' },
            { nivel: 2, classe: 'Warlock', escolhas: '⭐ Agonizing Blast (+CAR no dano do Eldritch Blast!)' },
            { nivel: 3, classe: 'Warlock', escolhas: '⭐ Pact of the Blade — conjura arma mágica' },
            { nivel: 4, classe: 'Warlock', escolhas: '⭐ Talento: +2 CAR → 18 ou Actor' },
            { nivel: 5, classe: 'Warlock', escolhas: 'Eldritch Blast 2 raios, Thirsting Blade (Extra Attack)' },
            { nivel: 6, classe: 'Warlock', escolhas: 'Dark One\'s Own Luck (+d10 em teste)' },
            { nivel: 7, classe: 'Warlock', escolhas: 'Hunger of Hadar (dano em área contínuo)' },
            { nivel: 8, classe: 'Warlock', escolhas: '⭐ Talento: +2 CAR → 20' },
            { nivel: 9, classe: 'Warlock', escolhas: 'Eldritch Blast 3 raios, spells de nível 5' },
            { nivel: 10, classe: 'Warlock', escolhas: 'Lifedrinker (+CAR no dano da arma)' },
            { nivel: 11, classe: 'Warlock', escolhas: 'Mystic Arcanum (6º nível)' },
            { nivel: 12, classe: 'Warlock', escolhas: 'Eldritch Blast 4 raios — dano massivo!' },
        ],
        combo: [
            'Hex + Eldritch Blast = dano absurdo a distância',
            'Pact of the Blade + melee quando precisar',
            'Hunger of Hadar em áreas de chokepoint',
            'Dark One\'s Blessing mantém HP alto matando inimigos'
        ],
        equipamentos: [
            { nome: 'Infernal Rapier', nota: 'Dano de fogo + CAR como atributo' },
            { nome: 'Potent Robe', nota: '+CAR no dano de cantrips' },
            { nome: 'Birthright', nota: '+2 CAR (até 22)' },
            { nome: 'Gloves of Dexterity', nota: 'DES fixa em 18' }
        ]
    },
    halsin: {
        id: 'halsin',
        name: 'Halsin',
        emoji: '🐻',
        role: 'Tank / Suporte',
        race: 'Wood Elf',
        class: 'Druid',
        subclass: 'Circle of the Moon',
        description: 'Mestre das formas selvagens. Forma de Urso Polar é um tanque absurdo com HP massivo. Cura quando precisa.',
        color: 'halsin',
        stats: {
            FOR: 10, DES: 14, CON: 15,
            INT: 10, SAB: 17, CAR: 12
        },
        estiloLuta: 'Wild Shape (Forma Selvagem)',
        background: 'Outlander (Athletics + Perception)',
        habilidadesChave: ['Wild Shape', 'Combat Wild Shape', 'Primal Strike', 'Elemental Wild Shape'],
        magias: ['Healing Word', 'Call Lightning', 'Conjure Woodland Beings', 'Moonbeam'],
        progressao: [
            { nivel: 1, classe: 'Druid', escolhas: 'Wild Shape, Spells: Healing Word, Thunderwave' },
            { nivel: 2, classe: 'Druid', escolhas: '⭐ Circle of the Moon — Combat Wild Shape (cura em forma animal!)' },
            { nivel: 3, classe: 'Druid', escolhas: 'Wild Shape: Bear, Moonbeam, Spike Growth' },
            { nivel: 4, classe: 'Druid', escolhas: '⭐ Talento: +2 SAB → 18 ou War Caster' },
            { nivel: 5, classe: 'Druid', escolhas: 'Wild Shape: Dire Raven, Conjure Animals' },
            { nivel: 6, classe: 'Druid', escolhas: 'Primal Strike (dano mágico em forma animal)' },
            { nivel: 7, classe: 'Druid', escolhas: 'Fire Elemental, Conjure Woodland Beings' },
            { nivel: 8, classe: 'Druid', escolhas: '⭐ Talento: +2 SAB → 20' },
            { nivel: 9, classe: 'Druid', escolhas: 'Wild Shape: Air/Earth Elemental' },
            { nivel: 10, classe: 'Druid', escolhas: 'Elemental Wild Shape (formas elementais!)' },
            { nivel: 11, classe: 'Druid', escolhas: 'Heal, Sunbeam' },
            { nivel: 12, classe: 'Druid', escolhas: '⭐ Thousand Forms ou +2 CON' },
        ],
        combo: [
            'Wild Shape: Bear = tanque massivo com HP extra',
            'Combat Wild Shape cura usando spell slots',
            'Moonbeam + Spike Growth = dano contínuo',
            'Forma de Elemental = dano + resistência'
        ],
        equipamentos: [
            { nome: 'Shapeshifter\'s Boon Ring', nota: '+d4 em testes em forma animal' },
            { nome: 'Armor of Moonbasking', nota: 'AC extra em Wild Shape' },
            { nome: 'Staff of the Ram', nota: 'Dano extra' },
            { nome: 'Amulet of Misty Step', nota: 'Mobilidade' }
        ]
    },
    minthara: {
        id: 'minthara',
        name: 'Minthara',
        emoji: '⚖️',
        role: 'DPS Melee / Suporte',
        race: 'Drow (Lolth-Sworn)',
        class: 'Paladin',
        subclass: 'Oath of Vengeance',
        description: 'Paladino de dano massivo. Divine Smite com crítico é devastador. Quebra juramento se quiser mais poder (Oathbreaker).',
        color: 'minthara',
        stats: {
            FOR: 16, DES: 10, CON: 14,
            INT: 10, SAB: 12, CAR: 16
        },
        estiloLuta: 'Great Weapon Fighting',
        background: 'Noble (Persuasion + Intimidation)',
        habilidadesChave: ['Divine Smite', 'Vow of Enmity', 'Aura of Protection', 'Improved Divine Smite'],
        magias: ['Shield of Faith', 'Thunderous Smite', 'Hold Person', 'Blinding Smite'],
        progressao: [
            { nivel: 1, classe: 'Paladin', escolhas: 'Divine Sense, Lay on Hands' },
            { nivel: 2, classe: 'Paladin', escolhas: '⭐ Divine Smite, Great Weapon Fighting' },
            { nivel: 3, classe: 'Paladin', escolhas: '⭐ Oath of Vengeance — Vow of Enmity (vantagem em 1 alvo!)' },
            { nivel: 4, classe: 'Paladin', escolhas: '⭐ Talento: Great Weapon Master' },
            { nivel: 5, classe: 'Paladin', escolhas: 'Extra Attack (2 ataques + 2 Smites!)' },
            { nivel: 6, classe: 'Paladin', escolhas: '⭐ Aura of Protection (+CAR nos saves)' },
            { nivel: 7, classe: 'Paladin', escolhas: 'Relentless Avenger (movimento extra após ataque)' },
            { nivel: 8, classe: 'Paladin', escolhas: '⭐ Talento: +2 FOR → 18 ou +2 CAR' },
            { nivel: 9, classe: 'Paladin', escolhas: 'Blinding Smite, spells de nível 3' },
            { nivel: 10, classe: 'Paladin', escolhas: 'Aura of Courage (imune a medo)' },
            { nivel: 11, classe: 'Paladin', escolhas: '⭐ Improved Divine Smite (+d8 radiante em todo ataque!)' },
            { nivel: 12, classe: 'Paladin', escolhas: '⭐ Talento: +2 FOR → 20 ou Savage Attacker' },
        ],
        combo: [
            'Vow of Enmity no chefe = vantagem em todos os ataques',
            'Critical + Smite de nível alto = dano ABSURDO',
            'Great Weapon Master com vantagem = destruição',
            'Aura of Protection protege a party inteira'
        ],
        equipamentos: [
            { nome: 'Sword of Justice', nota: 'Dano extra + AC' },
            { nome: 'Plate Armor', nota: 'AC máxima' },
            { nome: 'Gloves of the Growling Underdog', nota: 'Vantagem em melee' },
            { nome: 'Ring of Free Action', nota: 'Não pode ser paralisado' }
        ]
    },
    minsc: {
        id: 'minsc',
        name: 'Minsc',
        emoji: '🐹',
        role: 'DPS Melee',
        race: 'Human',
        class: 'Ranger',
        subclass: 'Beast Master',
        description: 'O guerreiro lendário com seu hamster Boo! Beast Master invoca um companheiro animal que luta junto.',
        color: 'minsc',
        stats: {
            FOR: 16, DES: 14, CON: 15,
            INT: 8, SAB: 10, CAR: 12
        },
        estiloLuta: 'Two-Weapon Fighting',
        background: 'Outlander (Athletics + Survival)',
        habilidadesChave: ['Animal Companion (Boo!)', 'Coordinated Attack', 'Exceptional Training', 'Bestial Fury'],
        magias: ['Hunter\'s Mark', 'Longstrider', 'Enhance Jump'],
        progressao: [
            { nivel: 1, classe: 'Ranger', escolhas: 'Favoured Enemy, Natural Explorer' },
            { nivel: 2, classe: 'Ranger', escolhas: 'Two-Weapon Fighting, Hunter\'s Mark' },
            { nivel: 3, classe: 'Ranger', escolhas: '⭐ Beast Master — Boo aparece! (companheiro animal)' },
            { nivel: 4, classe: 'Ranger', escolhas: '⭐ Talento: Dual Wielder (+1 AC, armas maiores)' },
            { nivel: 5, classe: 'Ranger', escolhas: 'Extra Attack, Boo fica mais forte' },
            { nivel: 6, classe: 'Ranger', escolhas: 'Coordinated Attack (Boo ataca junto!)' },
            { nivel: 7, classe: 'Ranger', escolhas: 'Exceptional Training (Boo mais inteligente)' },
            { nivel: 8, classe: 'Ranger', escolhas: '⭐ Talento: +2 FOR → 18' },
            { nivel: 9, classe: 'Ranger', escolhas: 'Spells de nível 3, Land\'s Stride' },
            { nivel: 10, classe: 'Ranger', escolhas: 'Hide in Plain Sight (stealth massivo)' },
            { nivel: 11, classe: 'Ranger', escolhas: '⭐ Bestial Fury (Boo ataca 2x!)' },
            { nivel: 12, classe: 'Ranger', escolhas: '⭐ Talento: +2 FOR → 20 ou Savage Attacker' },
        ],
        combo: [
            'Boo distrai inimigos = vantagem nos ataques de Minsc',
            'Dual wielding + Extra Attack = 3 ataques por turno',
            'Hunter\'s Mark em alvos prioritários',
            'Boo no nível 11 ataca 2x — dano extra!'
        ],
        equipamentos: [
            { nome: 'Sword of Chaos', nota: 'Dano variado + caótico' },
            { nome: 'Boo (Hamster)', nota: 'Companheiro animal insubstituível 🐹' },
            { nome: 'Medium Armor', nota: 'Bom AC com mobilidade' },
            { nome: 'Boots of Elvenkind', nota: 'Silencioso' }
        ]
    },
    jaheira: {
        id: 'jaheira',
        name: 'Jaheira',
        emoji: '🌿',
        role: 'Suporte / DPS Mágico',
        race: 'Half-Elf (High)',
        class: 'Druid',
        subclass: 'Circle of the Land',
        description: 'Druida versátil com foco em magias de controle e dano elemental. Mais magias que Moon, mas menos formas animais.',
        color: 'jaheira',
        stats: {
            FOR: 10, DES: 14, CON: 14,
            INT: 12, SAB: 17, CAR: 12
        },
        estiloLuta: 'N/A (Druid)',
        background: 'Soldier (Athletics + Intimidation)',
        habilidadesChave: ['Natural Recovery', 'Circle Spells', "Nature's Ward", 'Land's Stride'],
        magias: ['Call Lightning', 'Spike Growth', 'Conjure Animals', 'Ice Storm', 'Wall of Thorns'],
        progressao: [
            { nivel: 1, classe: 'Druid', escolhas: 'Wild Shape, Spells: Healing Word, Thunderwave' },
            { nivel: 2, classe: 'Druid', escolhas: '⭐ Circle of the Land — Natural Recovery (recupera slots!)' },
            { nivel: 3, classe: 'Druid', escolhas: 'Circle Spells extras (depende do terreno escolhido)' },
            { nivel: 4, classe: 'Druid', escolhas: '⭐ Talento: +2 SAB → 18 ou War Caster' },
            { nivel: 5, classe: 'Druid', escolhas: 'Call Lightning, Conjure Animals, 3º nível' },
            { nivel: 6, classe: 'Druid', escolhas: "Nature's Ward (imune a doença e plantas)" },
            { nivel: 7, classe: 'Druid', escolhas: 'Ice Storm, Fire Shield, 4º nível' },
            { nivel: 8, classe: 'Druid', escolhas: '⭐ Talento: +2 SAB → 20' },
            { nivel: 9, classe: 'Druid', escolhas: 'Wall of Stone, Conjure Elemental' },
            { nivel: 10, classe: 'Druid', escolhas: "Nature's Sanctuary (animais não atacam)" },
            { nivel: 11, classe: 'Druid', escolhas: 'Heal, Sunbeam, 6º nível' },
            { nivel: 12, classe: 'Druid', escolhas: '⭐ Talento: Resilient (CON) ou +2 CON' },
        ],
        combo: [
            'Natural Recovery = mais spell slots por dia',
            'Spike Growth + Call Lightning = dano contínuo absurdo',
            'Conjure Animals = tanques extras no campo',
            'Ice Storm pra slow e dano em área'
        ],
        equipamentos: [
            { nome: 'Staff of the Ram', nota: 'Dano extra + knockback' },
            { nome: 'Armor of Landfall', nota: 'AC + bônus de druida' },
            { nome: 'Ring of Twilight', nota: 'Stealth e proteção' },
            { nome: 'Broodmother\'s Revenge', nota: 'Dano extra' }
        ]
    }
};

// ===== Progressão por nível dos companions =====
function getCompanionLevelSummary(nivel) {
    const resumos = {
        astarion: {
            1: 'Rogue básico. Sneak Attack 1d6. Stealth é sua arma.',
            2: '⭐ Cunning Action. Hide como ação bônus!',
            3: '⭐ Assassin! Critical garantido em inimigos surpresos.',
            4: '⭐ Sharpshooter ou +2 DES. Dano massivo.',
            5: 'Sneak Attack 3d6 + Uncanny Dodge.',
            6: 'Expertise extra. Melhor em mais perícias.',
            7: 'Evasion. Dano de área reduzido pela metade.',
            8: '+2 DES → 20 ou Alert.',
            9: 'Sneak Attack 5d6. Dano subindo!',
            10: 'Talento extra. Flexibilidade.',
            11: 'Reliable Talent. Mínimo 10 nos dados de perícia.',
            12: 'Sneak Attack 6d6. Build completa.',
        },
        gale: {
            1: 'Wizard básico. Magic Missile e Shield.',
            2: '⭐ Evocation! Sculpt Spells não acerta aliados.',
            3: 'Fireball e Counterspell disponíveis!',
            4: '+2 INT → 18 ou War Caster.',
            5: '⭐ FIREBALL! Dano de área devastador.',
            6: 'Potent Cantrip. Cantrips mais fortes.',
            7: 'Conjure Elemental. Mais utilidade.',
            8: '+2 INT → 20. INT máxima!',
            9: 'Wall of Force. Controle de campo.',
            10: 'Empowered Evocation. +INT no dano.',
            11: 'Chain Lightning. Dano em área nivel 6.',
            12: 'Build completa. Mago devastador.',
        },
        wyll: {
            1: 'Warlock básico. Eldritch Blast + Dark One\'s Blessing.',
            2: '⭐ Agonizing Blast! +CAR no dano do EB.',
            3: '⭐ Pact of the Blade. Arma mágica com CAR!',
            4: '+2 CAR → 18.',
            5: 'Eldritch Blast 2 raios + Thirsting Blade.',
            6: 'Dark One\'s Own Luck. +d10 em teste.',
            7: 'Hunger of Hadar. Dano contínuo em área.',
            8: '+2 CAR → 20.',
            9: 'Eldritch Blast 3 raios.',
            10: 'Lifedrinker. +CAR no dano da arma.',
            11: 'Mystic Arcanum. Magia de 6º nível.',
            12: 'Eldritch Blast 4 raios. Build completa!',
        },
        halsin: {
            1: 'Druid básico. Wild Shape e Healing Word.',
            2: '⭐ Moon Druid! Combat Wild Shape cura.',
            3: 'Wild Shape: Bear. Tanque massivo!',
            4: '+2 SAB → 18.',
            5: 'Conjure Animals. Companheiros extra.',
            6: 'Primal Strike. Dano mágico em forma animal.',
            7: 'Conjure Woodland Beings. Mais invocações.',
            8: '+2 SAB → 20.',
            9: 'Wild Shape: Elemental. Poderoso!',
            10: 'Elemental Wild Shape. Novas formas.',
            11: 'Heal. Cura massiva.',
            12: 'Build completa. Tanque + healer.',
        },
        minthara: {
            1: 'Paladin básico. Lay on Hands.',
            2: '⭐ Divine Smite! Dano radiante explosivo.',
            3: '⭐ Vengeance. Vow of Enmity = vantagem!',
            4: '⭐ Great Weapon Master. +10 dano!',
            5: 'Extra Attack. 2 Smites por turno!',
            6: '⭐ Aura of Protection. Party salva mais.',
            7: 'Relentless Avenger. Mobilidade extra.',
            8: '+2 FOR → 18.',
            9: 'Blinding Smite. Controle + dano.',
            10: 'Aura of Courage. Imune a medo.',
            11: '⭐ Improved Smite! +d8 em todo ataque.',
            12: 'Build completa. DPS devastador.',
        },
        minsc: {
            1: 'Ranger básico. Boo ainda não apareceu.',
            2: 'Two-Weapon Fighting + Hunter\'s Mark.',
            3: '⭐ Beast Master! BOO APARECE! 🐹',
            4: '⭐ Dual Wielder. Armas maiores + 1 AC.',
            5: 'Extra Attack. 3 ataques por turno!',
            6: 'Coordinated Attack. Boo ataca junto!',
            7: 'Exceptional Training. Boo mais forte.',
            8: '+2 FOR → 18.',
            9: 'Spells de nível 3.',
            10: 'Hide in Plain Sight.',
            11: '⭐ Bestial Fury. Boo ataca 2x! 🐹🐹',
            12: 'Build completa. Minsc e Boo imparáveis!',
        },
        jaheira: {
            1: 'Druid básico. Healing Word e Thunderwave.',
            2: '⭐ Land Druid! Natural Recovery.',
            3: 'Circle Spells. Magias extras grátis.',
            4: '+2 SAB → 18.',
            5: 'Call Lightning. Dano sustentado.',
            6: "Nature's Ward. Imune a doença.",
            7: 'Ice Storm. Dano + slow em área.',
            8: '+2 SAB → 20.',
            9: 'Wall of Stone. Controle de campo.',
            10: "Nature's Sanctuary. Animais não atacam.",
            11: 'Heal + Sunbeam.',
            12: 'Build completa. Druida versátil.',
        }
    };
    return resumos[nivel];
}
